Fixed AttributeError when unpickling HTTPAdapterWithSocketOptions.
Azure/azure-kusto-python pull request #431
Opened 2022-11-09 16:04 UTC by creste

#### Pull Request Description

Fixes https://github.com/Azure/azure-kusto-python/issues/430

#### Future Release Comment
**Fixes:**
- Fixed Attribute error when unpickling HTTPAdapterWithSocketOptions

2022-11-09 16:13 UTC, creste commented
@microsoft-github-policy-service agree [company="Anonym"]

2022-11-09 16:14 UTC, creste commented
@microsoft-github-policy-service agree company="Anonym"

2022-11-16 13:07 UTC, AsafMah commented
Great job!

What about the other attributes? don't they also need pickling?

2022-11-16 14:45 UTC, creste commented
@AsafMah - Great question!

### pool_maxsize

`HTTPAdapterWithSocketOptions.pool_maxsize` does not need to be pickled because the base class, `HTTPAdapter`, uses and [pickles](https://github.com/psf/requests/blob/1e62a3ec18e19f85ddae03b4cbbdf0b4c62834c0/requests/adapters.py#L158-L159) [`_pool_maxsize`](https://github.com/psf/requests/blob/1e62a3ec18e19f85ddae03b4cbbdf0b4c62834c0/requests/adapters.py#L132) instead (note the underscore).  I'm _guessing_ `HTTPAdapterWithSocketOptions.pool_maxsize` exists to `pop()` `pool_maxsize` from `kwargs`, which forces `HTTPAdapter` to use the [`DEFAULT_POOLSIZE`](https://github.com/psf/requests/blob/1e62a3ec18e19f85ddae03b4cbbdf0b4c62834c0/requests/adapters.py#L139).

Alternatively, I can remove this line of code:
```python
self.pool_maxsize = kwargs.pop("pool_maxsize", None)
```
But that means `HTTPAdapter` will no longer use the [`DEFAULT_POOLSIZE`](https://github.com/psf/requests/blob/1e62a3ec18e19f85ddae03b4cbbdf0b4c62834c0/requests/adapters.py#L139).  I'm not sure if that will break something.

### max_retries
`HTTPAdapterWithSocketOptions.max_retries` is already [pickled](https://github.com/psf/requests/blob/1e62a3ec18e19f85ddae03b4cbbdf0b4c62834c0/requests/adapters.py#L158-L159) by [`HTTPAdapter`](https://github.com/psf/requests/blob/1e62a3ec18e19f85ddae03b4cbbdf0b4c62834c0/requests/adapters.py#L143-L146), so it doesn't need to be pickled by `HTTPAdapterWithSocketOptions.__getstate__()` again.

Similar to `pool_maxsize`, I can remove this line of code:
```python
self.max_retries = kwargs.pop("max_retries", None)
```
But that means `HTTPAdapter` will no longer use the default [`MAX_RETRIES`](https://github.com/psf/requests/blob/1e62a3ec18e19f85ddae03b4cbbdf0b4c62834c0/requests/adapters.py#L143-L144). I am not sure if that will break something.

2022-11-17 11:17 UTC, AsafMah commented
Great point!
That probably explains #429, it should be `get` instead of `pop`.

2022-11-20 06:23 UTC, AsafMah commented
Good point, yes, they could be just removed.

2022-11-20 13:39 UTC, AsafMah requested changes

2022-11-20 20:16 UTC, creste commented on azure-kusto-data/tests/test_http_adapter_with_socket_options.py
> +class HTTPAdapterWithSocketOptionsTests(unittest.TestCase):
Updated to use pytest.

2022-11-20 20:16 UTC, creste commented on azure-kusto-data/tests/test_http_adapter_with_socket_options.py
> +        pickle.loads(pickled)
Added assert to verify `socket_options` are picked and unpickled correctly.

2022-11-21 07:59 UTC, AsafMah commented
Awesome!

2022-11-21 07:59 UTC, AsafMah approved these changes

2022-11-21 08:01 UTC, merged