Add try except
Azure/azure-kusto-python pull request #486
Opened 2023-07-11 13:14 UTC by shira263

### Added 
Added new exception KustoNetworkError
Added try except in client and cloud_settings

2023-07-19 05:52 UTC, AsafMah requested changes

2023-07-23 07:29 UTC, shira263 commented on azure-kusto-data/tests/kusto_client_common.py
> +            file_name = "noFile.json"
Can you give an example for an actual call that fails? 
Why isn't it suitable to use a file that doesn't exist? this is exactly what we want to validate, a case which the "try" is not working and stepping into except.

2023-07-23 07:35 UTC, shira263 commented on azure-kusto-data/tests/test_token_providers.py
> +    def test_app_key_provider_whenURLnotValid():
Do you mean a test to test the changes in client? I added the tests for the client in test_kusto_client

2023-07-23 07:48 UTC, shira263 commented on azure-kusto-data/azure/kusto/data/exceptions.py
> +class KustoNetworkError(KustoServiceError):
Can you give an example to other exception that I can use as an reference? I used as a reference other exceptions that looks like what I implemented and does not contain endpoint or inner exception.

2023-07-23 08:40 UTC, AsafMah commented on azure-kusto-data/tests/kusto_client_common.py
> +            file_name = "noFile.json"
1. Spelling - "raiseNetwork"
2. `throw` an exception that is suitable for this case.

2023-07-23 08:40 UTC, AsafMah commented on azure-kusto-data/azure/kusto/data/exceptions.py
> +class KustoNetworkError(KustoServiceError):
See further down the file for more examples.
I want you to know how to write and use classes for the next assignment.

2023-07-23 08:42 UTC, AsafMah commented on azure-kusto-data/tests/test_token_providers.py
> +    def test_app_key_provider_whenURLnotValid():
What you currently have:
1. Unit test for the client
2. Integration test for cloud info

I want you to add an actual end-to-end test for the client.

Look at e2e.py (in azure-kusto-data).

Create a test that: 
1. Makes a client.
2. Uses an address that doesn't exist
3. Verify the exception being thrown.

Both sync and async.

2023-07-23 13:44 UTC, shira263 commented on azure-kusto-data/azure/kusto/data/exceptions.py
> +class KustoNetworkError(KustoServiceError):
Added the endpoint. The inner already exist when using 'from e' in client.py. Why do you prefer to pass it as a parameter instead?

2023-07-26 13:20 UTC, shira263 commented on azure-kusto-data/tests/test_token_providers.py
> +    def test_app_key_provider_whenURLnotValid():
Talked offline and agreed not to do.

2023-07-30 05:32 UTC, AsafMah commented on azure-kusto-data/azure/kusto/data/exceptions.py
> +class KustoNetworkError(KustoServiceError):
We discussed this, right?

2023-08-08 07:14 UTC, shira263 commented on azure-kusto-data/azure/kusto/data/exceptions.py
> +class KustoNetworkError(KustoServiceError):
If I recall correctly, you said we are not used to pass it as a parameter, but after I did some research, I saw that it is more common to use "from e"

2023-08-09 07:58 UTC, AsafMah commented on azure-kusto-data/azure/kusto/data/exceptions.py
> +class KustoNetworkError(KustoServiceError):
I'll clarify:

1. Currently you only put endpoint as part of the message, I want it to be a field so people can get it without parsing the error message.
2. Add the client request id as a member too

2023-08-09 07:59 UTC, AsafMah requested changes
see reply

2023-08-10 13:38 UTC, shira263 commented on azure-kusto-data/azure/kusto/data/exceptions.py
> +class KustoNetworkError(KustoServiceError):
1. But we do we use "from exception" in other parts of the code. 
Do you mean you want it to be a member for future use? 
2. Is it also relevant when we raise the error from _cloud_settings?

2023-08-10 13:51 UTC, AsafMah commented on azure-kusto-data/azure/kusto/data/exceptions.py
> +class KustoNetworkError(KustoServiceError):
I don't need the inner exception as a member, only what I said.
Client request id isn't available in cloud settings

2023-08-10 14:03 UTC, shira263 commented on azure-kusto-data/azure/kusto/data/exceptions.py
> +class KustoNetworkError(KustoServiceError):
1. Let's talk about it offline.
2. This is why I am asking

2023-08-13 09:21 UTC, AsafMah commented on azure-kusto-data/azure/kusto/data/exceptions.py
> +            "Failed to process network request for the endpoint: " + endpoint + "" if client_request_id is None else "Client Request ID:" + client_request_id
```suggestion
            "Failed to process network request for the endpoint: " + endpoint + ( "" if client_request_id is None else ("Client Request ID:" + client_request_id) )
```

2023-08-13 09:21 UTC, AsafMah submitted a review, later dismissed
Fix the suggestion and you can merge

2023-08-13 15:22 UTC, AsafMah approved these changes

2023-08-14 06:36 UTC, merged